apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.27.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: app
  name: app
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: app
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.27.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.network/backend: "true"
        io.kompose.service: app
    spec:
      containers:
        - command:
            - gunicorn
            - app:app
            - --bind=0.0.0.0:8000
            - --workers=4
            - --log-level=debug
            - --reload
          env:
            - name: AUTH_URL
              value: http://localhost/keycloak/realms/app/protocol/openid-connect/auth?client_id=app&response_type=code&redirect_uri=http://localhost/auth/callback
            - name: ISSUER_URL
              value: http://localhost/keycloak/realms/app
            - name: JWKS_URL
              value: http://localhost/keycloak/realms/app/protocol/openid-connect/certs
            - name: TOKEN_URL
              value: http://localhost/keycloak/realms/app/protocol/openid-connect/token
            - name: USERINFO_URL
              value: http://localhost/keycloak/realms/app/protocol/openid-connect/userinfo
          image: app
          name: app
          ports:
            - containerPort: 8000
          resources: {}
      restartPolicy: Always
status: {}
