apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.27.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: keycloak
  name: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: keycloak
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.27.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.network/backend: "true"
        io.kompose.service: keycloak
    spec:
      containers:
        - args:
            - -b=0.0.0.0
            - -Djboss.http.port=8080
          env:
            - name: DB_ADDR
              value: postgres
            - name: DB_DATABASE
              value: keycloak
            - name: DB_PASSWORD
            - name: DB_PORT
              value: "5432"
            - name: DB_USER
              value: admin
            - name: DB_VENDOR
              value: postgres
            - name: KEYCLOAK_IMPORT
              value: /realm-export.json
            - name: KEYCLOAK_PASSWORD
            - name: KEYCLOAK_USER
              value: admin
            - name: PROXY_ADDRESS_FORWARDING
              value: "true"
          image: jboss/keycloak:11.0.2
          name: keycloak
          ports:
            - containerPort: 8080
            - containerPort: 9990
          resources: {}
          volumeMounts:
            - mountPath: /opt/jboss/startup-scripts
              name: keycloak-claim0
            - mountPath: /realm-export.json
              name: keycloak-claim1
      restartPolicy: Always
      volumes:
        - name: keycloak-claim0
          persistentVolumeClaim:
            claimName: keycloak-claim0
        - name: keycloak-claim1
          persistentVolumeClaim:
            claimName: keycloak-claim1
status: {}
